### PR TITLE
#7 Pull Request Template

### LINKED ISSUE #7: Pull Request template
# User story
As a developer, I want to have access to a pull request template, so that the developers can make use of it whenever they are making a pull request.

## Acceptance criteria
- [ ] The pull request template has a header called `What the this pull request achieves`, in which the creator of the pull request specofoes the achievements of the pull request.
- [ ] The pull request also has a header named `Issues solved` in which the creator of the pull request can use the word `fixes` or `closes` followed by the issue number to close the issue that the pull request sloves. 
- [ ] The template needs to have an optional header named `Challanges faced` for the developer to write about the challanges.

### PR DESCRIPTION
**Pull request by amirpooya78**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
It introduces a pull request template 

* **What is the current behavior?** (You can also link to an open issue here)
with out template :)

* **What is the new behavior (if this is a feature change)?**
This cool PR Template :0

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?) 
 No

* **Does this PR close an issue (Mention the issue number and title)?** 
  
  closes #7 

* **Other information**:

### CODE REVIEW

**Comment by Aspanix** [comment]
It looks great, just 1 question. Is it always gonna be `closes #ISSUE-NUMBER`? what if there is a PR which doesn't close an issue but still contributes to an open issue? My suggestion is a multiple choice like:
- [ ] closes #ISSUE-NUMBER
- [ ] contributes #ISSUE-NUMBER

**Comment by amirpooya78** [comment]
> It looks great, just 1 question. Is it always gonna be `closes #ISSUE-NUMBER`? what if there is a PR which doesn't close an issue but still contributes to an open issue? My suggestion is a multiple choice like:
> 
> * [ ]  closes #ISSUE-NUMBER
> * [ ]  contributes #ISSUE-NUMBER

No, it is just for a hint if the PR closes an issue otherwise if a developer does not intend to close the issue he/she can just remove the statement

**Comment by Aspanix** [comment]
Oh i see, in the right information tab on this page it has a Development section which states the issue that this PR contributes to, so basically we won't be needing a `contribute #ISSUE-NUMBER`. 
Overall, well done it looks very good.

**Review by Aspanix — APPROVED** [review]
Good job!

**Pull request merged**
